### ISSUE TITLE
Blueprint::shardKey does not exist.

### ISSUE THREAD

**Issue by rana01645** [singlestore-labs/singlestoredb-laravel-driver#17]
Getting this error while trying to migrate!

`2014_10_12_000000_create_users_table .................................................................................................... 3ms FAIL

   BadMethodCallException

  Method Illuminate\Database\Schema\Blueprint::shardKey does not exist.`

**Comment by rana01645** [comment]
php -v
```
PHP 8.1.8 (cli) (built: Aug  1 2022 18:56:21) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.8, Copyright (c), by Zend Technologies
```

php artisan --version
`Laravel Framework 9.26.0`

**Comment by aarondfrancis** [comment]
Can you show me your `database.php` file? Laravel should be giving you an instance of `SingleStore\Laravel\Schema\Blueprint` not `Method Illuminate\Database\Schema\Blueprint`.

**Comment by rana01645** [comment]
Here it is

`<?php

use Illuminate\Support\Str;

return [

    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    'default' => env('DB_CONNECTION', 'singlestore'),

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => [

        'singlestore' => [
            'driver' => 'singlestore',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST'),
            'port' => env('DB_PORT'),
            'database' => env('DB_DATABASE'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD'),
            'unix_socket' => env('DB_SOCKET'),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
                PDO::ATTR_EMULATE_PREPARES => true,
                PDO::ATTR_PERSISTENT => true
            ]) : [],
        ],

        'sqlite' => [
            'driver' => 'sqlite',
            'url' => env('DATABASE_URL'),
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
        ],

        'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

        'pgsql' => [
            'driver' => 'pgsql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'search_path' => 'public',
            'sslmode' => 'prefer',
        ],

        'sqlsrv' => [
            'driver' => 'sqlsrv',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '1433'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            // 'encrypt' => env('DB_ENCRYPT', 'yes'),
            // 'trust_server_certificate' => env('DB_TRUST_SERVER_CERTIFICATE', 'false'),
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk haven't actually been run in the database.
    |
    */

    'migrations' => 'migrations',

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer body of commands than a typical key-value system
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
        ],

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'username' => env('REDIS_USERNAME'),
            'password' => env('REDIS_PASSWORD'),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_DB', '0'),
        ],

        'cache' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'username' => env('REDIS_USERNAME'),
            'password' => env('REDIS_PASSWORD'),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_CACHE_DB', '1'),
        ],

    ],

];
`

**Comment by rana01645** [comment]
Here is the database.php file of mine!

`https://gist.github.com/rana01645/838000e5265ec1c28338064588b22155`

By default database is importing Illuminate\Database\Schema\Blueprint, I also tried by using SingleStore\Laravel\Schema\Blueprint one, another issue arised like Schema::create is expecting the laravel's default one!

**Comment by aarondfrancis** [comment]
@rana01645 excellent, that looks right to me! 

Is there a `DB_CONNECTION` var in your `.env`?

**Comment by rana01645** [comment]
`DB_CONNECTION` was previously set to `mysql` in the `.env` file
After changing it to 
`DB_CONNECTION=singlestore` 

Seems like it's working fine! Thanks.

**Comment by rana01645** [comment]
Btw, I'm having hard time setting up github workflow with singlestore for testing the db in Laravel. The workflow example provided for `nodejs` is working fine! (https://github.com/rana01645/singlestore-and-github-actions-demo)

Where should I open a issue for this?

**Comment by aarondfrancis** [comment]
Glad we got that fixed! 

For the github workflow, are you mirroring the one in this repo (https://github.com/singlestore-labs/singlestoredb-laravel-driver/blob/main/.github/workflows/tests.yml) and having issues?

**Comment by rana01645** [comment]
No, I was trying with the node js one (https://github.com/rana01645/singlestore-and-github-actions-demo/blob/main/.github/workflows/singlestore-github-actions.yml)

Thanks for providing this one, It fixed my issue with the workflow!

**Comment by aarondfrancis** [comment]
Excellent, glad to hear it. Let me know if you run into anything else.

**Comment by rana01645** [comment]
Btw, I created a visible integration for Singlestore with a fresh Laravel project!

It also covers the automated database testing for Singlestore database with GitHub workflow.

Hope it will be helpful for someone who wants to quickstart Singlestore with Laravel.

https://github.com/rana01645/laravel-singlestore

Pull request with the necessary changes to get started
https://github.com/rana01645/laravel-singlestore/pull/1

**Comment by rana01645** [comment]
@aarondfrancis 

Is there any guideline related to using Singlestore in laravel sail?

**Comment by aarondfrancis** [comment]
Getting SingleStore running locally is outside the scope of this package, unfortunately. I have not used Laravel Sail!
