### ISSUE TITLE
Laravel can't find singlestore driver

### ISSUE THREAD

**Issue by larskoole** [singlestore-labs/singlestoredb-laravel-driver#2]
First of all, congrats on the package release!

I've found a bug the following bug.
<img width="713" alt="image" src="https://user-images.githubusercontent.com/8629456/171342221-dc9af32c-b6e3-4ea0-a837-b05f26e56932.png">

This gets thrown if you use database as your cache driver. In this case it was thrown because the `RouteServiceProvider.php` uses rate limiting which uses cache which uses the database.

My guess is that the RouteServiceProvider gets processed before the SingleStoreServiceProvider.

For the people running into this issue, you can solve it by adding the SingleStoreProvider code to your AppServiceProvider. Note: this is a temporary fix!
<img width="862" alt="image" src="https://user-images.githubusercontent.com/8629456/171343094-bbcb9dd9-c250-47a6-9186-fcbb8aba88fa.png">

**Comment by aarondfrancis** [comment]
Thanks for reporting! I'll get this cleaned up.

**Comment by aarondfrancis** [comment]
@larskoole Can you give me a little more info about your rate limiting setup? I did a fresh install, hit a route with default rate limiting, and am not running into any issues.

**Comment by aarondfrancis** [comment]
Hey @larskoole! Can you see if this is still happening with 0.0.3?

**Comment by fgilio** [comment]
I'm pretty sure this is the error I got before the package had auto discovery, so this should no longer be happening with 0.0.3.
We've this package running in 3 different proyects, working perfectly fine 🚀

**Comment by aarondfrancis** [comment]
I'm going to close this as I think it's resolved now, but please reopen it if that's not true!
