### ISSUE TITLE
Implement option to create sortKey desc index

### ISSUE THREAD

**Issue by srdante** [singlestore-labs/singlestoredb-laravel-driver#21]
After searching a bit about why my `ORDER BY x DESC` query was so slow in big tables even with a sort key, I found that sort keys by default work only for `ASC` queries. 

If I would like to take advantage of the sort key in a `DESC` query, I would need to create a table using the sort key desc, ex:

```sql
SORT KEY (Price desc)
```

But it seems the Laravel driver does not support setting the key orientation.

**Source:** https://www.singlestore.com/forum/t/optimizing-performance-of-order-by-x-desc-on-large-tables/2308/4.

**Comment by srdante** [comment]
I tried using `DB::raw`, but it didn't work:

```php
$table->sortKey(DB::raw('`created_at` DESC'));
```

Generated Value:
```sql
sort key(```created_at`` DESC`)
```

**Comment by carlsverre** [comment]
This is a good feature request. Will see about adding it to the driver. Thank you!
