### ISSUE TITLE
Can't define custom primary key for my shard key with autoIncrement id

### ISSUE THREAD

**Issue by srdante** [singlestore-labs/singlestoredb-laravel-driver#22]
From reading the title, it may seem confusing. But here is the table example:

```php
Schema::create('referral_commissions', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->foreignId('user_id')->shardKey();
    $table->foreignId('referral_id')->index();
    $table->integer('amount');
    $table->timestamp('created_at')->nullable();

    // Indexes
    $table->primary(['id', 'user_id']);
});
```

I'm actually trying to create this table with `user_id` as the shard key. According to SingleStore documentation, the shard key is a subset of the primary key. Taking this into consideration, I set the primary key as `id, user_id`.

But that does not work since Laravel always sets the increment value as the primary key. This migration is trying to create a table with two primary keys, leading to this SingleStore error:

```
General error: 1851 COLUMNAR indexes and SKIPLIST indexes cannot be used on the same table
```

Generated code:
```
CREATE TABLE
  `referral_commissions` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` bigint unsigned NOT NULL,
    `referral_id` bigint unsigned NOT NULL,
    `amount` int NOT NULL,
    `created_at` TIMESTAMP NULL,
    PRIMARY KEY `referral_commissions_id_user_id_primary` (`id`, `user_id`),
    INDEX `referral_commissions_referral_id_index` (`referral_id`),
    shard key (`user_id`)
  ) DEFAULT CHARACTER
SET
  utf8mb4 COLLATE 'utf8mb4_unicode_ci'
```

This problem does not seem to be related to the driver but to Laravel itself, which always sets the increment as the primary key. But I think it will be very hard to change this in the framework.

Maybe the SingleStore driver could prevent or control this kind of behavior.

**Comment by srdante** [comment]
@aarondfrancis What do you think would be the best way to solve this problem?

**Comment by srdante** [comment]
I was wondering if something like this would be possible:

```php
$table->bigIncrements('id')->withoutPrimaryKey();
```

**Comment by carlsverre** [comment]
I'm not a big fan of negating implicit behavior. What do you think about making `bigIncrements` *not* automatically make the auto_increment the primary key, and instead always requiring that the user declares the primary key on the table?

**Comment by carlsverre** [comment]
I.e. just making
```php
protected function modifyIncrement(Blueprint $blueprint, Fluent $column)
    {
        if (in_array($column->type, $this->serials) && $column->autoIncrement) {
            return 'auto_increment';
        }
    }
}```
