### ISSUE TITLE
Set custom variables (columnstore_segment_rows) to columnstore indexes

### ISSUE THREAD

**Issue by srdante** [singlestore-labs/singlestoredb-laravel-driver#23]
My application has a lot of frequent queries with specific where clauses. Learning about how to optimize the table for this kind of workload, I found that I would need to increase the number of segments, reducing the number of rows per segment.

I could do that by changing the global variable `columnstore_segment_rows`, but this would decrease a lot the compression amount for all tables, and this change is only needed for specific ones.

The global variable can be overwritten with this kind of syntax, setting the variable with the columstore index:
```sql
CREATE TABLE t (
    id INT, 
    SORT KEY (id) WITH (columnstore_segment_rows=100000)
);
```

But the Laravel driver does not support this kind of feature. It would be good to have something like:

```php
$table->id()->sortKey()->with('columnstore_segment_rows', 100000);
// OR
$table->sortKey('id')->with('columnstore_segment_rows', 100000);
```

I can try to make a Pull Request fo this feature if it's applicable.

**Source:**
https://docs.singlestore.com/managed-service/en/create-a-database/physical-database-schema-design/procedures-for-physical-database-schema-design/configuring-the-columnstore-to-work-effectively.html

**Comment by carlsverre** [comment]
I think supporting key options would be awesome. Will certainly push this driver farther away from the core Laravel API, but if you think it can fit safely in the logic, I am not opposed to your proposal.

Is it more idiomatic to do this:
```php
$table->sortKey('id')->with('columnstore_segment_rows', 100000);
```

Or something more like
```php
$table->sortKey('id')->withColumnstoreSegmentRows(100000);
```

Also note that SingleStore supports overriding this value globally as well as per table in case that helps.

**Comment by srdante** [comment]
@carlsverre I would personally go with the first syntax. I don't really know exactly all the possible variables for this "with" statement. 

Also what if SingleStore adds or removes a variable name? The lib would always be up to date. More work to maintain without a real benefit from my point of view.
