### ISSUE TITLE
Example sample

### ISSUE THREAD

**Issue by cAstraea** [singlestore-labs/singlestoredb-laravel-driver#35]
Do you happen to have a simple example project xD Probably doing something wrong but I'm stuck on the .env config part and getting 

**Unsupported driver [http].**

I'm running the docker container like so but not 100% sure what to fill in .env

**Comment by carlsverre** [comment]
I think this project should help you out: https://github.com/singlestore-labs/start-with-laravel

If you are still having issues, please re-open this issue and include your `.env` (with passwords redacted). Thanks!
