### ISSUE TITLE
Custom id column not working

### ISSUE THREAD

**Issue by bilalaslam777** [singlestore-labs/singlestoredb-laravel-driver#37]
In Laravel Migrations, _$table->id()_ always creates a column of type BIGINT(20). I am trying to use a custom numeric data type using following code in migrations.

`$table->mediumInteger("id", true, true);`

When using this package, it always creates a column of BIGINT datatype though the size is different e.g. BIGINT(8). I have tried other numeric data types like smallInteger, integer but they do not work.

I also tested in Laravel (without) this package and it works the way it suppose to. 

Am I missing something?

**Comment by carlsverre** [comment]
I just tested this and it seems to work? Maybe I am misunderstanding your issue/question. See this test for an example: https://github.com/singlestore-labs/singlestoredb-laravel-driver/pull/42/files#diff-f6da6c22d5e74ab81179bda2693633c2fb36619a61c3d97f857875f906c8fa1bR67
