### ISSUE TITLE
primaryKey does not exist

### ISSUE THREAD

**Issue by bilalaslam777** [singlestore-labs/singlestoredb-laravel-driver#38]
When creating the id **withoutPrimarykey** and then defining the primary key using **primaryKey** function throwing the following error.

**_Method SingleStore\Laravel\Schema\Blueprint::primaryKey does not exist._**

Following is the full code
```
Schema::create("some_table", function (Blueprint $table) {
                $table->integer("id", true, true)->withoutPrimaryKey();
                .........
                $table->timestamps();

                $table->primaryKey("id");
                $table->shardKey('id');
            });
```

**Comment by carlsverre** [comment]
Hmm... it appears we basically do this in our tests (https://github.com/singlestore-labs/singlestoredb-laravel-driver/blob/main/tests/Hybrid/CreateTable/IncrementWithoutPrimaryKeyTest.php#L23)

Can you make sure you are running the latest version of the driver and try wrapping `id` with an array: 
```
$table->primaryKey(["id"]);
```

**Comment by srdante** [comment]
@bilalaslam777 I think I know where this problem came from. It was a typo in the README example, there is no `primaryKey` method. To set a primary key using Laravel, the method is called only `primary`:

```php
$table->primary('id');
```

**Comment by carlsverre** [comment]
fixed in https://github.com/singlestore-labs/singlestoredb-laravel-driver/commit/9a5eef4f348278a4dc681035dce6ee64ffaaa8fe
