### ISSUE TITLE
Add support for the "change"-function

### ISSUE THREAD

**Issue by 4ice** [singlestore-labs/singlestoredb-laravel-driver#39]
It would be great if this feature was supported.

As I understand, the following would have to be done in order to change a field (This example changes a field called "name" from a varchar to text):

1. Add a column of the desired type (ALTER TABLE table_name ADD COLUMN field2 TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`; )
3. Fill values in this column with the column you want to change the data type (UPDATE table_name SET name2 = name;)
4. Remove the previous column (ALTER TABLE table_name DROP COLUMN name;)
5. Change the name of the new column (ALTER TABLE table_name CHANGE name2 name;)

Would it be possible to implement this? Or is there already another way to do this?

**Comment by carlsverre** [comment]
Does Laravel have a change function already that works with other database backends or are you just suggesting that this pattern should be made into a nice function?

**Comment by 4ice** [comment]
@carlsverre Yes, the function exists and works with other databases. I am migrating from mysql driver to singlestore, and I have several migrations that use the `change()`-function that I am working on rewriting as we speak.

**Comment by carlsverre** [comment]
Gotcha. This is a great feature request. Thank you!

**Comment by sneycampos** [comment]
Hi, any news about this issue/feature request?

**Comment by JackEllis** [comment]
@carlsverre I like this suggestion. Can this all be done in a single SQL DB transaction?

**Comment by carlsverre** [comment]
Unfortunately alter tables in SingleStore don't operate within user defined transactions. So it's not possible to perform this entire column change process atomically.

**Comment by hafezdivandari** [comment]
Is this issue still relevant? It seems that SingleStore supports [`alter table modify column`](https://docs.singlestore.com/cloud/reference/sql-reference/data-definition-language-ddl/alter-table/#:~:text=%7C%20MODIFY%20%5B,%3Ccollation_name%3E) just like MySQL?

If not, I can send a PR if you want. It's easy to implement this using the OP's workaround: adding, inserting, dropping, renaming.

**Comment by hafezdivandari** [comment]
You may check PR #88
