### ISSUE TITLE
Fix many things in Connection

### ISSUE THREAD

**Issue by szepeviktor** [singlestore-labs/singlestoredb-laravel-driver#4]
Hello @aarondfrancis!

```bash
composer require --dev nunomaduro/larastan
vendor/bin/phpstan analyze -c vendor/nunomaduro/larastan/extension.neon -l 5 src/
```

You will discover things like
```diff
diff --git a/src/Connect/Connection.php b/src/Connect/Connection.php
index 5c3e52e..14007af 100644
--- a/src/Connect/Connection.php
+++ b/src/Connect/Connection.php
@@ -6,18 +6,17 @@
 namespace SingleStore\Laravel\Connect;

 use Illuminate\Database\MySqlConnection;
-use SingleStore\Laravel\Query;
-use SingleStore\Laravel\QueryGrammar;
-use SingleStore\Laravel\Schema;
-use SingleStore\Laravel\SchemaBuilder;
-use SingleStore\Laravel\SchemaGrammar;
+use SingleStore\Laravel\Query\Builder as QueryBuilder;
+use SingleStore\Laravel\Query\Grammar as QueryGrammar;
+use SingleStore\Laravel\Schema\Builder as SchemaBuilder;
+use SingleStore\Laravel\Schema\Grammar as SchemaGrammar;

 class Connection extends MySqlConnection
 {
     /**
      * Get a schema builder instance for the connection.
      *
-     * @return SchemaBuilder
+     * @return \SingleStore\Laravel\Schema\Builder
      */
     public function getSchemaBuilder()
     {
@@ -25,36 +24,40 @@ class Connection extends MySqlConnection
             $this->useDefaultSchemaGrammar();
         }

-        return new Schema\Builder($this);
+        return new SchemaBuilder($this);
     }

     /**
      * Get the default query grammar instance.
      *
-     * @return QueryGrammar
+     * @return \Illuminate\Database\Grammar
      */
     protected function getDefaultQueryGrammar()
     {
-        return $this->withTablePrefix(new Query\Grammar);
+        return $this->withTablePrefix(new QueryGrammar);
     }

     /**
      * Get the default schema grammar instance.
      *
-     * @return SchemaGrammar
+     * @return \Illuminate\Database\Grammar
      */
     protected function getDefaultSchemaGrammar()
     {
-        return $this->withTablePrefix(new Schema\Grammar);
+        return $this->withTablePrefix(new SchemaGrammar);
     }

     /**
      * Get a new query builder instance.
+     *
+     * @return \SingleStore\Laravel\Query\Builder
      */
     public function query()
     {
-        return new Query\Builder(
-            $this, $this->getQueryGrammar(), $this->getPostProcessor()
+        return new QueryBuilder(
+            $this,
+            $this->getQueryGrammar(),
+            $this->getPostProcessor()
         );
     }
 }
```

Do you like static analysis?

**Comment by carlsverre** [comment]
I like this proposal, and would love to see something like phpstan/larastan in a pre-commit hook + part of CI/CD for the project. One question I have is the switch from things like `Schema\Grammar`  to `SchemaGrammar`. It doesnt seem like that should affect static analysis, just code style. Forgive me if I am missing something about PHP static analysis tools.

**Comment by szepeviktor** [comment]
Hello!
One should import all use classes. `Schema\Grammar` is relative. `SchemaGrammar` is imported.

**Comment by carlsverre** [comment]
Appreciate the information! It seems that to automatically resolve these issues requires a PHPStan pro subscription of which I do not have. If you have one could you submit a PR which resolves all of the issues?

**Comment by szepeviktor** [comment]
> to automatically resolve these issues requires a PHPStan pro subscription

No. It required only only the free version of PHPStan + a tiny bit of knowledge :)

**Comment by srdante** [comment]
Although these "fixes" are done by LaraStan. It is not related to static analysis, but code linting. You may find the same or a similar behavior with this PHP-CS-Fixer rule: https://cs.symfony.com/doc/rules/import/fully_qualified_strict_types.html

It does not really impact the code base. Also, the migration/schema part from Laravel is built in a very dynamic way, so a static analysis for this driver adapter will not have a significant impact. The best way to ensure the quality of this package is automatic testing, which is already implemented for all methods.

**Comment by szepeviktor** [comment]
All right, all right.
I'm a thinker, not a doer.
