### ISSUE TITLE
Support hash indexes

### ISSUE THREAD

**Issue by mpskovvang** [singlestore-labs/singlestoredb-laravel-driver#41]
It is not possible to use the `index` in a columnstore migration:

> COLUMNAR indexes and SKIPLIST indexes cannot be used on the same table

Would it be possible to detect and default to hash indexes automatically?

Alternatively add a new `hashIndex` or `usingHash` similar to `withoutPrimaryKey`.

```php
$table->sortKey();

$table->index(); // defaults to hash index
$table->index()->usingHash(); // or $table->index()->using('hash');
$table->hashIndex();
```

**Comment by carlsverre** [comment]
@srdante what do you think about this?

**Comment by carlsverre** [comment]
Sounds good. I like the idea of adding explicit keys the most, but also ok with the modifier. Would that be easy for you to add at some point?

**Comment by mpskovvang** [comment]
@srdante Good point regarding UNIQUE keys as well.

Apparently, only PRIMARY key defaults to hash behaviour. It automatically translates to `UNIQUE KEY PRIMARY (id) USING HASH`.

**Comment by srdante** [comment]
@carlsverre I went deep into the index migration code, and this option is already possible. The index method structure is:

```php
public function index($columns, $name = null, $algorithm = null)
```

The `$algorithm` parameter defines the `using x` statement. So the following code generates the index using hash:

```php
$table->index('name', 'my_name_index', 'hash');
```

**Comment by srdante** [comment]
I think it would be good to add a note about that in the README since its not mentioned in the Laravel documentation.
