### ISSUE TITLE
json_type is not a function

### ISSUE THREAD

**Issue by carlsverre** [singlestore-labs/singlestoredb-laravel-driver#43]
whereNull on a JSON expression generates this test `json_type(JSON_EXTRACT_JSON(data, 'value1')) = 'NULL'` which does not work in SingleStore.

Also: need to go through the tests in `JsonWhereTest.php` since it appears they aren't running against SingleStore. If they were, we would have caught this issue.

**Comment by fgilio** [comment]
Indeed, both [`where_null`](https://github.com/singlestore-labs/singlestoredb-laravel-driver/blob/main/tests/Hybrid/Json/JsonWhereTest.php#L106-L106) and [`where_not_null`](https://github.com/singlestore-labs/singlestoredb-laravel-driver/blob/main/tests/Hybrid/Json/JsonWhereTest.php#L118) are not running against SingleStore and only assert that the SQL string matches the expected one (which is wrong).

Can you share the SQL that will work on SingleStore?

**Comment by carlsverre** [comment]
One way you can do it is try to extract as string - if the value is a literal "json null" then you will get back a SingleStore NULL.
```
MemSQL [test]> select json_extract_string(j, '') is null from j;
+------------------------------------+
| json_extract_string(j, '') is null |
+------------------------------------+
|                                  1 |
+------------------------------------+
1 row in set (0.053 sec)

MemSQL [test]> select json_extract_string(j, '') from j;
+----------------------------+
| json_extract_string(j, '') |
+----------------------------+
| NULL                       |
+----------------------------+
1 row in set (0.036 sec)```

The other option is `json_get_type`:
```
MemSQL [test]> select json_get_type(j) = "null" from j;
+---------------------------+
| json_get_type(j) = "null" |
+---------------------------+
|                         1 |
+---------------------------+
1 row in set (0.037 sec)```
