### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by schaeferalex** [singlestore-labs/singlestoredb-laravel-driver#54]
Laravel 10 has been released today (https://laravel-news.com/laravel-10). This package currently doesn't support it, please add support for Laravel 10. Thanks!

**Comment by AdalbertMemSQL** [comment]
Hi Alexander,

Thanks for the request. I will try to investigate this next week.

**Comment by schaeferalex** [comment]
Thanks for getting this done so quickly!
