### ISSUE TITLE
Unpublished Laravel 10 Support

### ISSUE THREAD

**Issue by jadgray** [singlestore-labs/singlestoredb-laravel-driver#59]
Hi Guys, 

Thanks for updating to support Laravel 10; just a quick one, but you still need to do a release for this update. Could you please publish this new version? 

If there's a release I'm unaware of, I do appolagise. 

CC @AdalbertMemSQL

**Comment by AdalbertMemSQL** [comment]
Hi @jadgray 
The release will be published soon :)

**Comment by jadgray** [comment]
@AdalbertMemSQL Awesome, thanks for your work 👍🏻
