### ISSUE TITLE
Redundant primary keys

### ISSUE THREAD

**Issue by AmirHossein** [singlestore-labs/singlestoredb-laravel-driver#76]
I can see that version 1.5.2 generates 2 primary keys for sample migration below:
```php
Schema::create('table_name', function (Blueprint $table) {
    $table->string('name');
    $table->unsignedBigInteger('valu');

    $table->primary('name');
});
```
Sql is:
```sql
create table `table_name` (
    `name` varchar(255) not null,
    `val` bigint unsigned not null,
    primary key `table_name_name_primary`(`name`),
    primary key (`name`)
) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
```

which throws SQL error like below:
`General error: 1851 COLUMNAR indexes and SKIPLIST indexes cannot be used on the same table `

I would appreciate it if you could check it.

**Comment by AmirHossein** [comment]
It seems the package missed [this update](https://github.com/laravel/framework/pull/49374/files#diff-68f714a9f1b751481b993414d3f1300ad55bcef12084ec0eb8f47f350033c24b) from a recent [PR](https://github.com/laravel/framework/pull/49374).

**Comment by AdalbertMemSQL** [comment]
Hey @AmirHossein 
You are right. I'm going to work on a fix.
