### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by schaeferalex** [singlestore-labs/singlestoredb-laravel-driver#81]
Laravel 11 has been released (https://laravel-news.com/laravel-11). Unfortunately, this package does not currently support it. Please add support for Laravel 11. Thank you!

**Comment by AdalbertMemSQL** [comment]
Done in this [PR](https://github.com/singlestore-labs/singlestoredb-laravel-driver/pull/82)

**Comment by schaeferalex** [comment]
Thank you!
