### ISSUE TITLE
SQLSTATE[HY000] [2002] Operation timed out

### ISSUE THREAD

**Issue by LucasNCastro** [singlestore-labs/singlestoredb-laravel-driver#83]
Hello, 

we have been encountering this error since we upgraded to SingleStore version 8.5.15:

```
Illuminate\Database\QueryException /cliRuntime.php in {closure}
SQLSTATE[HY000] [2002] Operation timed out (SQL: select * from `user` where `user`.`id` = 2251799845008727 limit 1)
```

The timeout appears randomly on different queries.

Environment :

Vapor : Lamba Serverless
PHP : 8.1
Laravel : 9.21
Cluster SingleStore Cloud (Helios) : 8.5.15
singlestoredb/singlestoredb-laravel : 1.5.4

Are you also experiencing the same error?

**Comment by AdalbertMemSQL** [comment]
Hi @LucasNCastro ,
Checked this locally and didn't get this error.

**Comment by AdalbertMemSQL** [comment]
I believe this error is caused by the connectivity issue between the client and the database, not by the driver itself.
